RMSE:

Root    (To undo the square)
Mean    (Average)
Square  ()
Error   ()

In [11]:
import cv2
import numpy as np

img1=cv2.imread('/home/student/CSC106/Weeks/Week13/panda1.jpg')
img2=cv2.imread('/home/student/CSC106/Weeks/Week13/panda2.jpg')

img1=cv2.cvtColor(img1, cv2.COLOR_BGR2GRAY)
img2=cv2.cvtColor(img2, cv2.COLOR_BGR2GRAY)

def mse(img1, img2):
    h, w =img1.shape
    diff=cv2.subtract(img1,img2)
    err=np.sum(diff**2)
    mse=err/(float(h*w))
    return mse,diff

error, diff=mse(img1,img2)
print(error, diff)

70.689616 [[128 155 162 ... 182 169 166]
 [175 192 150 ... 181 168 166]
 [193 192 122 ... 178 175 175]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]
